trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: lljochemll/quirks:latest

steps:
- script: |
    dub upgrade
    dub test -b unittest-cov
    bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  displayName: 'Generate code coverage'
  env:
    CODECOV_TOKEN: $(CODECOV_TOKEN)