trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: lljochemll/quirks:latest

steps:
- checkout: self
  clean: true
  persistCredentials: true

- script: |
    rm -rf /docs
    rm docs.json
    dub upgrade
    dub build -b ddox
    cp -R ./docs ~/temp/docs
  displayName: 'Build documentation'

- script: |
    git config user.email "dev.azure.com"
    git config user.name "Azure Pipelines"
    git checkout gh-pages
  displayName: 'Switch to gh-pages branch'

- script: |
    rm -rf .
    cp -R ~/temp/docs .
    git add -A
    git commit -m "[skip ci] Update docs"
    git push
  displayName: 'Push documentation'