trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: lljochemll/quirks:latest

steps:
- checkout: self
  clean: true
  persistCredentials: true

- script: |
    git checkout -b master
  displayName: 'Switch to docs branch'

- script: |
    rm -rf /docs
    rm docs.json
    dub upgrade
    dub build -b ddox
  displayName: 'Build documentation'

- script: |
    git commit -m "[skip ci] Update docs"
    git push
  displayName: 'Push documentation'