trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: dlang2/dmd-ubuntu:latest

steps:
- script: |
    git checkout -b docs
  displayName: 'Switch to docs branch'

- script: |
    dub upgrade
    dub build -b ddox
  displayName: 'Build documentation'

- script: |
    apt-get install hub
    git commit -m "[skip ci] Update docs"
    git push
    hub pull-request --base OWNER:master -m "Update docs"
  displayName: 'Create pull request'