trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: lljochemll/quirks:latest

steps:
- script: |
    git checkout -b master
  displayName: 'Switch to docs branch'

- script: |
    dub upgrade
    dub build -b ddox
  displayName: 'Build documentation'

- script: |
    git commit -m "[skip ci] Update docs"
    git push
  displayName: 'Push documentation'