name: ci

on:
  push:
  branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        dmd_version: [2.088.0, 2.087.1, 2.087.0]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    
    - name: Install DMD ${{ matrix.dmd_version }}
      uses: WebFreak001/setup-dmd@v1
      with:
        dmd-version: ${{ matrix.dmd_version }}
        
    - name: Test
      run: dub test -b unittest-cov
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
