name: ci

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        dmd_version: [2.089.0, 2.088.1, 2.088.0]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    
    - name: Install DMD
      uses: WebFreak001/setup-dmd@v1
      with:
        dmd-version: ${{ matrix.dmd_version }}
        
    - name: Test
      run: dub test
      
    

  codecov:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install DMD
      uses: WebFreak001/setup-dmd@v1
      with:
        dmd-version: 2.088.0

    - name: Test
      run: dub test -b unittest-cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}

