name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        dmd_version: [2.092.0, 2.091.1, 2.090.1, 2.089.1, 2.088.1]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Install DMD
      uses: WebFreak001/setup-dmd@v1
      with:
        dmd-version: ${{ matrix.dmd_version }}
        
    - name: Test
      run: dub test
   
  codecov:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install DMD
      uses: WebFreak001/setup-dmd@v1
      with:
        dmd-version: 2.091.0

    - name: Test
      run: dub test -b unittest-cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        token: ${{secrets.CODECOV_TOKEN}}

